#!/usr/bin/env php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Orchestra\Testbench\Concerns\CreatesApplication;
use Orchestra\Testbench\Concerns\HandlesRoutes;
use Recca0120\LaravelParallel\Console\ParallelCommand;
use Recca0120\LaravelParallel\Tests\Fixtures\setupDatabase;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

require_once __DIR__ . '/../../vendor/autoload.php';

$laravel = new class()
{
    use CreatesApplication;
    use setupDatabase;
    use HandlesRoutes;

    private $app;

    protected function getEnvironmentSetUp($app)
    {
        $app['config']['auth.guards.api'] = [
            'driver' => 'token',
            'provider' => 'users',
            'hash' => false,
        ];

        $this->databaseSetUp($app);
    }

    protected function defineRoutes($router): void
    {
        $router->middleware('web')->get('/', function (Request $request) {
            return $request->isJson()
                ? response()->json(['content' => 'Hello World'])
                : 'Hello World';
        });

        $router->middleware('web')->get('/previous_url', function () {
            return app('session')->previousUrl();
        });

        $router->middleware('web')->get('/server_variables', function () {
            return Request::capture()->server->all();
        });

        $router->middleware('web')->get('/status_code/{code}', function ($code) {
            abort($code);
        });

        $router->middleware('web')->get('/echo', function () {
            echo 'echo foo';

            return 'bar';
        });

        $router->middleware('web')->get('/dump', function () {
            dump('dump(foo)');

            return 'bar';
        });

        $router->middleware('web')->get('/dd', function () {
            dd('dd(foo)');
        });

        $router->middleware('web')->post('/auth/login', function (Request $request) {
            return Auth::attempt($request->only('email', 'password')) ? Auth::user() : [];
        });

        $router->middleware('web', 'auth')->post('/user', function (Request $request) {
            $user = $request->user();
            $reflect = new ReflectionClass($user);
            $property = $reflect->getProperty('attributes');
            $property->setAccessible(true);

            return response()->json($property->getValue($user));
        });

        $router->middleware('web')->patch('/session', function (Request $request) {
            Session::put('session', $request->get('session'));

            return ['success' => true];
        });

        $router->middleware('web')->get('/session', function () {
            return ['session' => Session::get('session')];
        });

        $router->middleware('web')->get('/sleep', function () {
            sleep(random_int(1, 3));

            return ['success' => true];
        });

        $router->middleware('auth:api')->post('/api/user', function (Request $request) {
            return response()->json($request->user());
        });

        $router->middleware('web')->get('/date', function (Request $request) {
            return Carbon::now()->toIso8601String();
        });
    }

    public function getApplication()
    {
        $this->app = $this->createApplication();

        $this->setUpApplicationRoutes($this->app);

        return $this->app;
    }
};

class EchoCommand extends Command
{
    protected static $defaultName = 'echo';

    protected function configure(): void
    {
        $this->addArgument('string', InputArgument::REQUIRED);
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $output->write($input->getArgument('string'));

        return 0;
    }
}

$application = new Application();
$application->add(new ParallelCommand($laravel->getApplication()));
$application->add(new EchoCommand());
$application->run();
